### ISSUE TITLE
Вопрос про коллажи

### ISSUE THREAD

**Issue by Klemeshov** [Elizaneu/MyWardrobe#21]
Нужен ли вывод всех коллажей(не только пользователя) и если да, то как их сортировать? по лайкам или по по дате создания, а может по стилю или сезону?

**Comment by Elizaneu** [comment]
Вывод всех коллажей нужен. 
На home page нужно еженедельно обновлять 6 лучших коллажей по количеству лайков.
При поиске сортировка происходит двумя способами: либо по трем критериям: стиль/сезон/дресс-код, либо по категориям одежды, входящей в коллаж.
